setting-up-investment-calculator-chart
jvin08/crypto-app-j pull request #63
Opened 2024-05-17 13:59 UTC by jvin08

2024-05-17 15:41 UTC, yoloOnTheBattlefield requested changes, later dismissed

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/Header.tsx
> +  const dateNow = new Date(priceDate).toLocaleString("default", { month: "long" }).slice(0,3) + " " + new Date(priceDate).getDate() + ", " + new Date(priceDate).getUTCFullYear();
const day = new Date(priceDate)
const dateNow = day.toLocaleString("default", { month: "long" }).slice(0,3) + " " + day.getDate() + ", " + day.getUTCFullYear();

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/SpentAmount.tsx
> +  getChartData(chartData);
useEffect(() => {getChartData(chartData);} )

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/SpentAmount.tsx
> +  getChartData(chartData);
[chartData]

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/SpentAmount.tsx
> +  getChartData(chartData);
put the chartData as dependency

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/SpentAmountDCA.tsx
> +  getChartData(chartData);
same here

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/ValueCostAverage.tsx
> +          }</button>
make it a reusable component

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/options.ts
> +  const prices = data.map((item:number[])=>item[0]);
const [time, prices] = data.reduce(
  (acc, [price, time]) => ({
    time: [...acc.time, formatStandardDate(new Date(time))],
    prices: [...acc.prices, price]
  }),
  { time: [], prices: [] }
);

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/utils.ts
> +  return [Math.floor(spentAmount), Math.floor(actualGrowArray.slice(-1)?.[0]), growArrayWithTime];
return {
spentAmount: Math.floor(spentAmount),
lastValue: Math.floor(actualGrowArray.slice(-1)?.[0]),
totalInvestements: growArrayWithTime
}

2024-05-17 15:41 UTC, yoloOnTheBattlefield commented on app/components/investCalculator/utils.ts
>  };
same here

2024-05-18 01:25 UTC, jvin08 reviewed
fixed

2024-05-18 01:26 UTC, merged